# This is a basic workflow to help you get started with Actions

name: CI with java and gradle

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #setup java
      - name : setup jdk 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: checkout code
        uses: actions/checkout@v2
     # make gradlew executable 
      - name: make gradlew executable
        run: chmod +x ./gradlew
     # run build using gradle
      - name: Build with Gradle
        run: ./gradlew build -x test -x checkstyle -x spotbugs 
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name : setup jdk 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public
    - name: Gradle unit tests
      run: ./gradlew run test

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name : setup jdk 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public
    - name: Gradle checkstyle
      run: ./gradlew run checkstyle
      
  spotbugs:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name : setup jdk 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public
    - name: Gradle spotbugs
      run: ./gradlew run spotbugsMain
    
